### ISSUE TITLE
Error in integration

### ISSUE THREAD

**Issue by deReede** [eifinger/hass-weenect#256]
## Version of the custom_component
3.0.1

## Describe the bug
I've installed the HACS plugin. And added the integration via the integration panel in HA.
It asked for credentials en I've put in the Weenect e-mail and password and it accepted.
Then it was trying to start/connect and within a second:
<img width="203" alt="image" src="https://github.com/eifinger/hass-weenect/assets/78696834/478187e2-efde-477a-b753-80fe13b2de7f">

I am currently on HA version:
<img width="300" alt="image" src="https://github.com/eifinger/hass-weenect/assets/78696834/5738eaff-121b-4c75-920a-8f281894db74">

## Debug log
<img width="692" alt="image" src="https://github.com/eifinger/hass-weenect/assets/78696834/d8664953-ea03-488b-958b-e9a653bf24be">

**Comment by eifinger** [comment]
Thank you for opening an issue.
Could you please click on the error you have screenshotted under `Debug log` and provide me with the stacktrace which should be shown there?

**Comment by deReede** [comment]
<img width="652" alt="image" src="https://github.com/eifinger/hass-weenect/assets/78696834/ea1c2cf1-e9b7-4bdc-8edb-ad5f6600fbf5">

**Comment by deReede** [comment]
I had contact with Weenect support, and it turned out that the module wasn't activated correctly. They did remote reset of the SIM and suddenly the integration started working too. So I've closed the ticket. Thank you for your time and for creating this nice plugin!

**Comment by walkxcode** [comment]
![image](https://github.com/eifinger/hass-weenect/assets/71191962/78386bfd-897e-470f-b28d-083428e31afc)

**Comment by eifinger** [comment]
@walkxcode could you please open a new issue with debug information?
I added additional debug statements since this issue occured last time

**Comment by eifinger** [comment]
<img width="410" alt="Screenshot 2023-08-17 at 08 18 39" src="https://github.com/eifinger/hass-weenect/assets/1481961/e8e67d66-49d6-4440-98b7-ef8c988aee19">
<img width="303" alt="Screenshot 2023-08-17 at 08 20 00" src="https://github.com/eifinger/hass-weenect/assets/1481961/a0d6906b-fcdd-4434-8123-c9f1dac228b7">
