### ISSUE TITLE
Failed setup, will retry

### ISSUE THREAD

**Issue by walkxcode** [eifinger/hass-weenect#303]
Made per request of @eifinger in #256 

## Version of the custom_component
Latest version (3.2.0)

## Describe the bug
I have just installed the integration from HACS, the login works correctly, but after logging in I am greeted with the error: `expected string or bytes-like object, got 'NoneType'; Retrying in background`. Other than that there are no errors to be found.

## Debug log

![download](https://github.com/eifinger/hass-weenect/assets/71191962/34d32880-5b43-4d4e-956d-0b56050c5cbe)

**Comment by eifinger** [comment]
If you have enabled debug logging there has to be another log statement starting with `Failed to update weenect data:`

**Comment by walkxcode** [comment]
No, this is all I am getting.

**Comment by eifinger** [comment]
Could you please follow the instructions under  https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics and upload the log file here?

**Comment by walkxcode** [comment]
[home-assistant_weenect_2023-08-25T09-15-06.177Z.log](https://github.com/eifinger/hass-weenect/files/12437545/home-assistant_weenect_2023-08-25T09-15-06.177Z.log)

**Comment by eifinger** [comment]
Perfect thank you. I understand what the problem is now. Will provide a fix in the coming days

**Comment by eifinger** [comment]
The issue should be fixed. Feel free to comment or reopen the issue when it still occurs
